config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.with_rich_text_content_and_embeds
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NagarajBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
  </head>

  <body>
  
  <div id="wrapper">

  <!-- Header -->
    <header id="header">
      <div class="inner">

        <!-- Logo -->
          <a href="index.html" class="logo">
            <span class="symbol"><img src="images/logo.svg" alt="" /></span><span class="title">Nagaraj</span>
          </a>

        <!-- Nav -->
          <nav>
            <ul>
              <li><a href="#menu">Menu</a></li>
            </ul>
          </nav>

      </div>
    </header>

  <!-- Menu -->
    <nav id="menu">
      <h2>Menu</h2>
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="generic.html">Ipsum veroeros</a></li>
        <li><a href="generic.html">Tempus etiam</a></li>
        <li><a href="generic.html">Consequat dolor</a></li>
        <li><a href="elements.html">Elements</a></li>
      </ul>
    </nav>
    <%= yield %>
    <!-- Footer -->
    <footer id="footer">
      <div class="inner">
        <section>
          <h2>Get in touch</h2>
          <form method="post" action="#">
            <div class="fields">
              <div class="field half">
                <input type="text" name="name" id="name" placeholder="Name" />
              </div>
              <div class="field half">
                <input type="email" name="email" id="email" placeholder="Email" />
              </div>
              <div class="field">
                <textarea name="message" id="message" placeholder="Message"></textarea>
              </div>
            </div>
            <ul class="actions">
              <li><input type="submit" value="Send" class="primary" /></li>
            </ul>
          </form>
        </section>
        <section>
          <h2>Follow</h2>
          <ul class="icons">
            <li><a href="#" class="icon brands style2 fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="#" class="icon brands style2 fa-facebook-f"><span class="label">Facebook</span></a></li>
            <li><a href="#" class="icon brands style2 fa-instagram"><span class="label">Instagram</span></a></li>
            <li><a href="#" class="icon brands style2 fa-dribbble"><span class="label">Dribbble</span></a></li>
            <li><a href="#" class="icon brands style2 fa-github"><span class="label">GitHub</span></a></li>
            <li><a href="#" class="icon brands style2 fa-500px"><span class="label">500px</span></a></li>
            <li><a href="#" class="icon solid style2 fa-phone"><span class="label">Phone</span></a></li>
            <li><a href="#" class="icon solid style2 fa-envelope"><span class="label">Email</span></a></li>
          </ul>
        </section>
        <ul class="copyright">
          <li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
      </div>
    </footer>
    </div>
    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="main">
  <div class="inner">
    <h1>Editing Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<div id="main">
  <div class="inner">
    <header>
      <h1>Hai, I am nagaraj from chennai. Having good experience in Audits & Mechanics. <br/></h1>
      <p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
    </header>
    <section class="tiles">
      <% @posts.each do |post| %>
        <article class="style1">
          <span class="image">
            <img src="images/pic01.jpg" alt="" />
          </span>
          <a href="<%= post_path(post) %>">
            <h2><%= post.title %></h2>
            <div class="content">
            </div>
          </a>
        </article>
      <%end %>
    </section>
    <% if current_user.present? %>
      <p> <%= link_to 'New Post', new_post_path %> </p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div id="main">
  <div class="inner">
    <h1>New Post</h1>
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
  <div id="main">
    <div class="inner">
      <h1>  <%= @post.title %> </h1>
      <p>   <%= @post.content %> </p>
    </div>
  </div>